# Load DSL and set up stages
require "capistrano/setup"

require "capistrano/deploy"
require 'capistrano/file-permissions'

require "capistrano/scm/git"
install_plugin Capistrano::SCM::Git

require 'capistrano/symfony'
require 'capistrano/composer'
require 'slackistrano/capistrano'
require 'capistrano/yarn'

Dir.glob("lib/capistrano/tasks/*.rake").each { |r| import r }
