app:
    resource: '@AppBundle/Controller/'
    type: annotation

login_check:
    path: /login
    methods: ['POST']

logout:
    path: /logout

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
